package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
)

// aspectPreset holds per-aspect kohya LoRA hyperparameter baselines.
// Overridable per dataset via datasets.config_json (v2 — merged manually for
// now, the column exists so nothing blocks it).
type aspectPreset struct {
	NetworkDim   int
	NetworkAlpha int
	Note         string
}

var kAspectPresets = map[string]aspectPreset{
	"face":        {32, 16, "Face detail benefits from higher rank."},
	"hair":        {16, 8, ""},
	"jewelry":     {16, 8, "Concrete-detail aspect — mixing in external reference photos measurably helps."},
	"lingerie":    {16, 8, "Concrete-detail aspect — mixing in external reference photos measurably helps."},
	"environment": {16, 8, "Prefer more images with fewer repeats over the reverse."},
	"style":       {8, 4, "Low rank keeps a style LoRA from memorizing content."},
	"composition": {8, 4, ""},
	"pose": {16, 8, "NOTE: the app's OpenPose ControlNet is the right tool for pose control — " +
		"a pose LoRA only reinforces pose *vocabulary* (promptable poses), it will not fix adherence."},
	"hands": {16, 8, "Honest expectation: LoRAs rarely fix hands. Expect marginal gains at best."},
}

var defaultPreset = aspectPreset{16, 8, ""}

// POST /api/datasets/{id}/build — freeze the dataset into a self-contained
// kohya-ss package under /data/datasets/<name>/.
func (s *server) handleDatasetBuild(w http.ResponseWriter, r *http.Request) {
	id := r.PathValue("id")
	d, err := s.scanDataset(s.db.QueryRow(datasetSelect+" WHERE d.id = ?", id))
	if err != nil {
		writeErr(w, http.StatusNotFound, "dataset not found")
		return
	}
	model := modelByID(d.BaseModel)
	if model == nil || model.Ckpt == "" {
		writeErr(w, http.StatusBadRequest, "dataset base model has no checkpoint")
		return
	}

	aspectName := ""
	if d.AspectID != nil {
		s.db.QueryRow("SELECT name FROM aspects WHERE id = ?", *d.AspectID).Scan(&aspectName)
	}
	preset := defaultPreset
	if p, ok := kAspectPresets[aspectName]; ok {
		preset = p
	}

	rows, err := s.db.Query(`
		SELECT di.image_id, i.sha256 FROM dataset_items di
		JOIN images i ON i.id = di.image_id
		WHERE di.dataset_id = ? AND i.blob_present = 1`, d.ID)
	if err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	type item struct{ imageID, sha string }
	var items []item
	for rows.Next() {
		var it item
		if err := rows.Scan(&it.imageID, &it.sha); err != nil {
			rows.Close()
			writeErr(w, http.StatusInternalServerError, err.Error())
			return
		}
		items = append(items, it)
	}
	rows.Close()
	if len(items) == 0 {
		writeErr(w, http.StatusBadRequest, "dataset has no images with blobs")
		return
	}

	root := filepath.Join(s.dataDir, "datasets", d.Name)
	imgDir := filepath.Join(root, "img")
	if err := os.RemoveAll(root); err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	if err := os.MkdirAll(imgDir, 0o755); err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}

	// Copy blobs + write caption .txt files; freeze captions into dataset_items.
	missingCaptions := 0
	for _, it := range items {
		caption, err := s.effectiveCaption(it.imageID)
		if err != nil {
			writeErr(w, http.StatusInternalServerError, err.Error())
			return
		}
		if caption == "" {
			missingCaptions++
		}
		full := d.TriggerWord
		if caption != "" {
			full = d.TriggerWord + ", " + caption
		}
		if err := copyFile(s.blobPath(it.sha), filepath.Join(imgDir, it.sha+".png")); err != nil {
			writeErr(w, http.StatusInternalServerError, "copy blob: "+err.Error())
			return
		}
		if err := os.WriteFile(filepath.Join(imgDir, it.sha+".txt"), []byte(full+"\n"), 0o644); err != nil {
			writeErr(w, http.StatusInternalServerError, err.Error())
			return
		}
		if _, err := s.db.Exec(`
			UPDATE dataset_items SET caption = ? WHERE dataset_id = ? AND image_id = ?`,
			full, d.ID, it.imageID); err != nil {
			writeErr(w, http.StatusInternalServerError, err.Error())
			return
		}
	}

	outputName := fmt.Sprintf("%s_%s_v1", nonEmpty(aspectName, d.Name), ecoShort(model.Ecosystem))
	if strings.Contains(strings.ToLower(outputName), "flux") {
		// Load-bearing app constraint: the Ol1nLLM LoRA family filter treats any
		// filename containing "flux" as a Flux LoRA and hides it from SDXL pickers.
		outputName = strings.ReplaceAll(strings.ToLower(outputName), "flux", "fx")
	}

	datasetToml := fmt.Sprintf(`# Generated by finetune-gallery for dataset %q
[general]
enable_bucket = true
min_bucket_reso = 640
max_bucket_reso = 1536
bucket_reso_steps = 64
caption_extension = ".txt"

[[datasets]]
resolution = 1024
batch_size = 2
keep_tokens = 1        # trigger word stays first through caption shuffle

  [[datasets.subsets]]
  image_dir = "%s"
  num_repeats = %d
  shuffle_caption = true
`, d.Name, "/dataset/img", d.Repeats)

	trainToml := fmt.Sprintf(`# Generated by finetune-gallery — SDXL LoRA baseline for aspect %q
# Checkpoint path is resolved on the GPU box via ${CKPT_DIR} (see train/run.sh).
pretrained_model_name_or_path = "%s"
output_dir = "/dataset/output"
output_name = "%s"
save_model_as = "safetensors"

network_module = "networks.lora"
network_dim = %d
network_alpha = %d

learning_rate = 1e-4
unet_lr = 1e-4
text_encoder_lr = 5e-5
lr_scheduler = "cosine_with_restarts"
lr_warmup_steps = 100
optimizer_type = "AdamW8bit"

max_train_epochs = 10
save_every_n_epochs = 2
mixed_precision = "bf16"
save_precision = "bf16"
gradient_checkpointing = true
cache_latents = true
# cache_text_encoder_outputs stays OFF: incompatible with caption shuffle +
# text-encoder training.
min_snr_gamma = 5
seed = 42
`, nonEmpty(aspectName, d.Name), "__CKPT_DIR__/"+model.Ckpt, outputName,
		preset.NetworkDim, preset.NetworkAlpha)

	note := preset.Note
	if note != "" {
		note = "\n> " + note + "\n"
	}
	captionWarn := ""
	if missingCaptions > 0 {
		captionWarn = fmt.Sprintf(
			"\n⚠️  %d/%d images had NO caption (trigger word only). Auto-caption or hand-caption them and rebuild for better results.\n",
			missingCaptions, len(items))
	}
	readme := fmt.Sprintf(`# Dataset %s

- aspect: %s
- base model: %s (%s, ecosystem %s)
- trigger word: %s
- images: %d, repeats: %d
- network dim/alpha: %d/%d
%s%s
## Train (on the GPU box, from the finetune-gallery repo)

    make -C train train DATASET=%s

which runs kohya sd-scripts:

    accelerate launch sdxl_train_network.py \
      --config_file /dataset/train_config.toml \
      --dataset_config /dataset/dataset.toml

Expected output: output/%s.safetensors — the runner copies it into ComfyUI
models/loras/ where the Ol1nLLM app picks it up automatically (SDXL family:
filename must NOT contain "flux").

## Ecosystem compatibility

The LoRA will work on models in the %q ecosystem. Cross-ecosystem use degrades
quality — train a sibling dataset per target ecosystem instead.
`, d.Name, nonEmpty(aspectName, "—"), d.BaseModel, model.Ckpt, model.Ecosystem,
		d.TriggerWord, len(items), d.Repeats, preset.NetworkDim, preset.NetworkAlpha,
		note, captionWarn, d.Name, outputName, model.Ecosystem)

	files := map[string]string{
		"dataset.toml":      datasetToml,
		"train_config.toml": trainToml,
		"README.md":         readme,
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(root, name), []byte(content), 0o644); err != nil {
			writeErr(w, http.StatusInternalServerError, err.Error())
			return
		}
	}

	if _, err := s.db.Exec(
		"UPDATE datasets SET status = 'built', built_at = datetime('now') WHERE id = ?", d.ID); err != nil {
		writeErr(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"path":            root,
		"imageCount":      len(items),
		"missingCaptions": missingCaptions,
		"outputName":      outputName + ".safetensors",
	})
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	if _, err := io.Copy(out, in); err != nil {
		out.Close()
		return err
	}
	return out.Close()
}

func nonEmpty(v, fallback string) string {
	if v != "" {
		return v
	}
	return fallback
}

// ecoShort maps an ecosystem to the short tag used in LoRA filenames.
func ecoShort(eco string) string {
	switch eco {
	case "sdxl-base":
		return "sdxl"
	case "illustrious":
		return "illust"
	default:
		return eco
	}
}
